# Generated by Django 3.1.2 on 2020-10-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=5)),
                ('english', models.CharField(max_length=50)),
                ('ukrainian', models.CharField(max_length=50)),
                ('russian', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_short', models.CharField(max_length=3)),
                ('english', models.CharField(max_length=50)),
                ('ukrainian', models.CharField(max_length=50)),
                ('russian', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=3)),
                ('english', models.CharField(max_length=50)),
                ('ukrainian', models.CharField(max_length=50)),
                ('russian', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrackMart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=20)),
                ('track_date', models.DateTimeField()),
                ('point_id', models.CharField(max_length=5)),
                ('status_id', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=5)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_tracker.city')),
                ('country_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_tracker.country')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=20)),
                ('track_date', models.DateTimeField()),
                ('is_actual_track', models.BooleanField(max_length=20)),
                ('is_actual_status', models.BooleanField(max_length=20)),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_tracker.trackpoint')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_tracker.statuses')),
            ],
        ),
    ]
